export type CheckoutApplicationError = {
  code: string;
  message: string;
};

export const CHECKOUT_ERROR_CODES = {
  MERCHANT_NOT_FOUND: "MERCHANT_NOT_FOUND",
  MERCHANT_NOT_ACCEPTING: "MERCHANT_NOT_ACCEPTING",
  EMPTY_CART: "EMPTY_CART",
  INVALID_LINE: "INVALID_LINE",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  PRODUCT_FOREIGN_MERCHANT: "PRODUCT_FOREIGN_MERCHANT",
  PRODUCT_NOT_SELLABLE: "PRODUCT_NOT_SELLABLE",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  INVALID_OPTION_SELECTION: "INVALID_OPTION_SELECTION",
  INVALID_FULFILLMENT: "INVALID_FULFILLMENT",
  PICKUP_UNAVAILABLE: "PICKUP_UNAVAILABLE",
  DELIVERY_ZONE_REQUIRED: "DELIVERY_ZONE_REQUIRED",
  DELIVERY_ZONE_NOT_SERVED: "DELIVERY_ZONE_NOT_SERVED",
  DELIVERY_MINIMUM_NOT_MET: "DELIVERY_MINIMUM_NOT_MET",
  DELIVERY_ADDRESS_REQUIRED: "DELIVERY_ADDRESS_REQUIRED",
  PAYMENT_METHOD_INVALID: "PAYMENT_METHOD_INVALID",
  CONTACT_INVALID: "CONTACT_INVALID",
  IDEMPOTENCY_KEY_INVALID: "IDEMPOTENCY_KEY_INVALID",
} as const;

export type CheckoutErrorCode =
  (typeof CHECKOUT_ERROR_CODES)[keyof typeof CHECKOUT_ERROR_CODES];

export function checkoutError(
  code: CheckoutErrorCode,
  message: string,
): CheckoutApplicationError {
  return { code, message };
}
