import type { CheckoutReview } from "./checkout-review";

export type CheckoutApplicationError = {
  code: string;
  message: string;
  /** Present when the live quote changed after the client reviewed it. */
  review?: CheckoutReview;
};

export const CHECKOUT_ERROR_CODES = {
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  ACCOUNT_UNAVAILABLE: "ACCOUNT_UNAVAILABLE",
  MERCHANT_NOT_FOUND: "MERCHANT_NOT_FOUND",
  MERCHANT_NOT_ACCEPTING: "MERCHANT_NOT_ACCEPTING",
  MERCHANT_CLOSED: "MERCHANT_CLOSED",
  EMPTY_CART: "EMPTY_CART",
  INVALID_LINE: "INVALID_LINE",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  PRODUCT_FOREIGN_MERCHANT: "PRODUCT_FOREIGN_MERCHANT",
  PRODUCT_NOT_SELLABLE: "PRODUCT_NOT_SELLABLE",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  INVALID_OPTION_SELECTION: "INVALID_OPTION_SELECTION",
  INVALID_FULFILLMENT: "INVALID_FULFILLMENT",
  PICKUP_UNAVAILABLE: "PICKUP_UNAVAILABLE",
  DELIVERY_ZONE_REQUIRED: "DELIVERY_ZONE_REQUIRED",
  DELIVERY_ZONE_NOT_SERVED: "DELIVERY_ZONE_NOT_SERVED",
  DELIVERY_MINIMUM_NOT_MET: "DELIVERY_MINIMUM_NOT_MET",
  DELIVERY_ADDRESS_REQUIRED: "DELIVERY_ADDRESS_REQUIRED",
  PAYMENT_METHOD_INVALID: "PAYMENT_METHOD_INVALID",
  CONTACT_INVALID: "CONTACT_INVALID",
  IDEMPOTENCY_KEY_INVALID: "IDEMPOTENCY_KEY_INVALID",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  CHECKOUT_REVIEW_REQUIRED: "CHECKOUT_REVIEW_REQUIRED",
  CHECKOUT_PAYLOAD_INVALID: "CHECKOUT_PAYLOAD_INVALID",
  ORDER_PERSISTENCE_FAILED: "ORDER_PERSISTENCE_FAILED",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_ALREADY_CANCELED: "ORDER_ALREADY_CANCELED",
  ORDER_NOT_CANCELABLE: "ORDER_NOT_CANCELABLE",
  INVALID_CANCEL_REASON: "INVALID_CANCEL_REASON",
  DELIVERY_STATE_CONFLICT: "DELIVERY_STATE_CONFLICT",
} as const;

export type CheckoutErrorCode =
  (typeof CHECKOUT_ERROR_CODES)[keyof typeof CHECKOUT_ERROR_CODES];

export function checkoutError(
  code: CheckoutErrorCode,
  message: string,
  review?: CheckoutReview,
): CheckoutApplicationError {
  return review ? { code, message, review } : { code, message };
}
