import { timestamp, uuid } from "drizzle-orm/pg-core";

/** UUID primary keys generated by PostgreSQL (gen_random_uuid). */
export const idColumn = () => uuid("id").defaultRandom().primaryKey().notNull();

/** Absolute instants as timestamptz — never browser-local wall time. */
export const createdAtColumn = () =>
  timestamp("created_at", { withTimezone: true, mode: "date" })
    .defaultNow()
    .notNull();

export const updatedAtColumn = () =>
  timestamp("updated_at", { withTimezone: true, mode: "date" })
    .defaultNow()
    .notNull();

export const timestamps = {
  createdAt: createdAtColumn(),
  updatedAt: updatedAtColumn(),
};
